################################################################################
#####     Copy dinput8.dll and dinput8.ini into the main DDDA folder.      #####
################################################################################
#####                               Settings                               #####
################################################################################
[main]
### Character customization screen (Secret of Metamorphosis)
###  - allows you to enter this screen at any time
###  - replaces Manual menu (on the very first screen when you launch the game)
###  - you need to enter the menu with keyboard, it doesnt work with mouse
charCustomization = off

### prevents camera from autocorrecting when moving around with sheathed weapon
disableAutoCam = on

### extends the vertical range you can view with the camera
extendVerticalCam = on

### turns windowed mode into borderless fullscreen
borderlessFullscreen = off

### stop the game from pausing when the window losses focus
disablePauseOnFocusLoss = off

### Load additional library
###  - use only in case you know what you're doing (set dll name)
###  - calls LoadLibrary for the specified dll
loadLibrary =

[hotkeys]
enabled = on

### https://msdn.microsoft.com/en-us/library/windows/desktop/dd375731.aspx
### set to 0xFF to disable
### default: Insert = in-game ui (see below)
keyUI = 0x2D

[inGameUI]
### In-game UI (overlay)
###  - should work with enb, may not work with steam overlay etc
###  - overlay for tweaking stuff, press keyUI (above) to show (default Insert)
enabled = on

[cheats]
### you can equip anything, ignoring vocation restriction
ignoreEquipVocation = off

[server]
### Server hooks
###  - changes the game server that is used for pawn rental and online Ur-Dragon
###  - 'enabled' - turns this feature 'on'/'off'
###  - 'host' - the name of the server (default: dune.dragonsdogma.com)
###  - 'port' - the port of the server (default: 12501)
enabled = off
host = dune.dragonsdogma.com
port = 12501

################################################################################
#####                               Credits                                #####
################################################################################
### MinHook - The Minimalistic x86/x64 API Hooking Library:                  ###
###     https://github.com/TsudaKageyu/minhook                               ###
### ImGui (in-game overlay):                                                 ###
###     https://github.com/ocornut/imgui                                     ###
### Most of cheats + camera stuff:                                           ###
###     http://forum.cheatengine.org/viewtopic.php?p=5641841#5641841         ###
################################################################################
